name = "Demo Modpack"
author = "JaegyuDev, TylenolWasTaken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5c3759da77fc1d40859cf51feeaaeb9364f251709e09e77b1464f302c544f84"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
